### ISSUE TITLE
Use red-yellow-green colour gradiant (?)

### ISSUE THREAD

**Issue by davidmegginson** [SimonbJohnson/hdx-ebola-ipc-gap-map#4]
Do you think it would make sense to change the colour scheme on this visualisation to range from red to yellow to green, instead of dark red to light red?

I know that that's non-trivial, because it's not actually a non-contiguous colour gradient, but I think that seeing traffic-light colours (especially green-ish for an area with good coverage) could provide better feedback to viewers.

Have you ever tried that approach?  Did it work?

**Comment by davidmegginson** [comment]
Lots of discussion here, including the benefit of going exponential rather than linear: http://stackoverflow.com/questions/4161369/html-color-codes-red-to-yellow-to-green

**Comment by SimonbJohnson** [comment]
@davidmegginson This is an easy change to make as it picks the colour from a list.  Generally though I try to vary lightness or saturation so that people with colour blindness can still differentiate the scale. I use this site to generate my scales http://colorbrewer2.org/

I'm happy to make the change though if you think none of these are suitable.

**Comment by davidmegginson** [comment]
Excellent reminder about accessibility -- thanks.  With that in mind, perhaps a red->blue scale would work better than a red->green one; I think the important thing is to have a colour that signals success as well as one that signals failure.

What do you think of this scheme?

http://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=9

**Comment by SimonbJohnson** [comment]
@davidmegginson That looks good.  I'll implement.  Do you want this used on other dashboards for consistency, such as the data quality one?

**Comment by davidmegginson** [comment]
I think a monochromatic scheme is still good for http://simonbjohnson.github.io/hdx-ebola-ipc-drilldown/ — it's not a bad/good visualisation, so traffic-light colouring would not make as much sense.  And you're already using traffic-light colouring on http://simonbjohnson.github.io/hdx-ebola-ipc-quality/

So please just go ahead and change http://simonbjohnson.github.io/hdx-ebola-ipc-gap-map/ to use the pseudo-traffic-light colouring (with blue instead of green, for colour blindness) that I linked above.  Thanks!

**Comment by SimonbJohnson** [comment]
@davidmegginson new colour scheme http://simonbjohnson.github.io/hdx-ebola-ipc-gap-map/

**Comment by davidmegginson** [comment]
Looks great!  When you zoom in on Nzerekore (which I'll be able to bookmark when #5 is done), you can really see the difference.
